"""Task template service - simplified to two core types."""
from pathlib import Path
from typing import Dict, Optional
from datetime import datetime


class TaskTemplates:
    """Task template generators - simplified to two types."""
    
    @staticmethod
    def generate_simple_script(
        script_content: str,
        working_dir: str = "",
        env_vars: str = "{}",
    ) -> str:
        """Generate a simple one-time execution script.
        
        This is the default template for regular scheduled tasks.
        The script executes once per cron cycle and exits.
        """
        import json
        
        try:
            env_dict = json.loads(env_vars) if env_vars else {}
        except:
            env_dict = {}
        
        env_lines = []
        if env_dict:
            for key, value in env_dict.items():
                escaped = str(value).replace('"', '\\"')
                env_lines.append(f'export {key}="{escaped}"')
        
        env_section = "\n".join(env_lines) if env_lines else ""
        cd_section = f'cd "{working_dir}"' if working_dir else ""
        
        return f'''#!/bin/bash
# Auto-generated by Script Monitor - Simple Task
# Type: One-time execution (runs per cron schedule)
# Created: {datetime.now().isoformat()}

set -e

echo "========================================"
echo "[$$(date '+%Y-%m-%d %H:%M:%S')] Task started"
echo "----------------------------------------"

{env_section}

{cd_section}

# User script content
{script_content}

echo "----------------------------------------"
echo "[$$(date '+%Y-%m-%d %H:%M:%S')] Task completed"
echo "========================================"
'''
    
    @staticmethod
    def generate_daemon_script(
        target_script: str,
        process_name: str,
        pid_file: Optional[str] = None,
        working_dir: str = "",
        env_vars: str = "{}",
        auto_restart: bool = True,
        restart_delay: int = 5,
        max_restarts: int = 3,
    ) -> str:
        """Generate a daemon wrapper script.
        
        This template wraps an existing script and monitors the process.
        It will automatically restart the process if it crashes (up to max_restarts).
        
        Args:
            target_script: Path to the script to wrap and monitor
            process_name: Name used to identify the process (for pgrep)
            pid_file: Custom PID file path (auto-generated if not provided)
            working_dir: Working directory for execution
            env_vars: Environment variables in JSON format
            auto_restart: Whether to auto-restart on crash
            restart_delay: Seconds to wait before restart
            max_restarts: Maximum restart attempts per check cycle
        """
        import json
        
        # Generate default PID file if not provided
        if not pid_file:
            safe_name = process_name.replace(' ', '_').replace('/', '_')
            pid_file = f"/tmp/script_monitor_daemon_{safe_name}.pid"
        
        try:
            env_dict = json.loads(env_vars) if env_vars else {}
        except:
            env_dict = {}
        
        env_lines = []
        if env_dict:
            for key, value in env_dict.items():
                escaped = str(value).replace('"', '\\"')
                env_lines.append(f'export {key}="{escaped}"')
        
        env_section = "\n".join(env_lines) if env_lines else ""
        cd_section = f'cd "{working_dir}"' if working_dir else ""
        
        restart_logic = ""
        if auto_restart:
            restart_logic = f"""
    echo "进程已停止，开始自动重启..."
    RESTART_COUNT=0
    while [ $RESTART_COUNT -lt {max_restarts} ]; do
        echo "重启尝试 ($((RESTART_COUNT + 1))/{max_restarts})..."
        
        # Execute target script in background
        (
            {env_section}
            {cd_section}
            exec bash "{target_script}"
        ) &
        NEW_PID=$!
        
        echo "启动中，PID: $NEW_PID"
        sleep {restart_delay}
        
        # Check if still running
        if ps -p "$NEW_PID" > /dev/null 2>&1; then
            # Verify it's the right process
            if [ -n "$PROCESS_NAME" ]; then
                if pgrep -f "$PROCESS_NAME" | grep -qw "$NEW_PID"; then
                    echo "$NEW_PID" > "$PID_FILE"
                    echo "✓ 重启成功，新 PID: $NEW_PID"
                    exit 0
                fi
            else
                echo "$NEW_PID" > "$PID_FILE"
                echo "✓ 重启成功，新 PID: $NEW_PID"
                exit 0
            fi
        fi
        
        RESTART_COUNT=$((RESTART_COUNT + 1))
        echo "重启失败，等待 {restart_delay} 秒后重试..."
        sleep {restart_delay}
    done
    
    echo "✗ 达到最大重启次数 ({max_restarts})，停止重启"
    rm -f "$PID_FILE"
    exit 1"""
        else:
            restart_logic = """
    echo "进程已停止，自动重启已禁用"
    rm -f "$PID_FILE"
    exit 0"""
        
        return f'''#!/bin/bash
# Auto-generated by Script Monitor - Daemon Task  
# Type: Daemon (monitors and auto-restarts process)
# Target Script: {target_script}
# Process Name: {process_name}
# Created: {datetime.now().isoformat()}

set -e

PID_FILE="{pid_file}"
PROCESS_NAME="{process_name}"
TARGET_SCRIPT="{target_script}"

echo "========================================"
echo "[$$(date '+%Y-%m-%d %H:%M:%S')] Daemon check: $PROCESS_NAME"
echo "PID File: $PID_FILE"
echo "Target: $TARGET_SCRIPT"
echo "----------------------------------------"

# Check for existing PID file
if [ -f "$PID_FILE" ]; then
    SAVED_PID=$(cat "$PID_FILE")
    echo "Found saved PID: $SAVED_PID"
    
    # Verify process is still running
    if ps -p "$SAVED_PID" > /dev/null 2>&1; then
        # Double-check it's the right process
        if [ -n "$PROCESS_NAME" ]; then
            if pgrep -f "$PROCESS_NAME" | grep -qw "$SAVED_PID"; then
                echo "✓ Process running normally (PID: $SAVED_PID)"
                echo "========================================"
                exit 0
            else
                echo "⚠ PID $SAVED_PID exists but not target process (PID reuse suspected)"
            fi
        else
            echo "✓ Process running normally (PID: $SAVED_PID)"
            echo "========================================"
            exit 0
        fi
    else
        echo "PID $SAVED_PID process not found"
    fi
    
    # Clean up stale PID file
    rm -f "$PID_FILE"
else
    echo "No PID file found, checking for running instance..."
fi

# Check if process is already running (by name)
if [ -n "$PROCESS_NAME" ]; then
    EXISTING_PID=$(pgrep -f "$PROCESS_NAME" | head -1)
    if [ -n "$EXISTING_PID" ]; then
        echo "Found running instance (PID: $EXISTING_PID), updating PID file"
        echo "$EXISTING_PID" > "$PID_FILE"
        echo "========================================"
        exit 0
    fi
fi

echo "Process not running, starting..."

# Start or restart the process
{restart_logic}

echo "========================================"
'''


def generate_script(
    task_type: str,
    script_content: Optional[str] = None,
    target_script: Optional[str] = None,
    process_name: Optional[str] = None,
    **kwargs
) -> str:
    """Generate script based on task type.
    
    Args:
        task_type: 'simple' or 'daemon'
        script_content: For simple tasks, the actual script content
        target_script: For daemon tasks, path to script to wrap
        process_name: For daemon tasks, process identifier
        **kwargs: Additional parameters
        
    Returns:
        Generated script content
    """
    if task_type == 'daemon':
        if not target_script or not process_name:
            raise ValueError("Daemon tasks require target_script and process_name")
        return TaskTemplates.generate_daemon_script(
            target_script=target_script,
            process_name=process_name,
            **kwargs
        )
    else:
        # Simple task
        if not script_content:
            raise ValueError("Simple tasks require script_content")
        return TaskTemplates.generate_simple_script(
            script_content=script_content,
            **kwargs
        )


def get_template_info() -> list:
    """Get information about available templates."""
    return [
        {
            "id": "simple",
            "name": "单次执行任务",
            "description": "按 Cron 调度执行脚本，执行完成后退出。适合定时备份、数据同步、报告生成等任务。",
            "features": [
                "按 Cron 表达式定时执行",
                "支持环境变量配置",
                "自动记录执行日志",
                "执行完成后自动退出"
            ]
        },
        {
            "id": "daemon", 
            "name": "守护进程任务",
            "description": "包装已有脚本为守护进程，持续监控进程状态，崩溃后自动重启。适合长期运行的服务。",
            "features": [
                "PID 文件跟踪进程状态",
                "进程崩溃自动检测",
                "可配置自动重启策略",
                "支持最大重启次数限制",
                "双重验证防止 PID 重用"
            ]
        }
    ]
